dist: trusty
sudo: false
language: generic
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
install:
  - conda env create --quiet --file=environment.yml
  - source activate library-access
script:
  - pytest
